    create table if not exists comments (
       id int8 generated by default as identity,
        comment TEXT not null,
        post_id int8,
        user_id int8,
        primary key (id)
    );
    create table if not exists posts (
       id int8 generated by default as identity,
        likes bigint not null,
        photo TEXT not null,
        title TEXT not null,
        user_id int8,
        primary key (id)
    );
    create table if not exists user_roles (
       id int8 generated by default as identity,
        role varchar(255),
        username varchar(255),
        user_id int8,
        primary key (id)
    );

    create table if not exists users (
       id int8 generated by default as identity,
        enabled boolean not null,
        main_photo varchar(255),
        password varchar(255),
        username varchar(255),
        primary key (id)
    );